### ISSUE TITLE
connect error "status: 'Error: getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by Khalid-Alqahtani** [OutsourcedGuru/octo-client#2]
Hi 

I have Ubuntu OS and I install Octoprint on it and I can access Octoprint using 
http://0.0.0.0:5000
or
http://localhost:5000'

when I tried to use the connect method 
I face errors 
{ status: 'Error: getaddrinfo ENOTFOUND http://0.0.0.0:5000' }
{ status: 'Error: getaddrinfo ENOTFOUND http://localhost:5000' }

my config.js file 

exports.hostName =  'http://0.0.0.0:5000';
exports.apiKey =    'REDACTED';
or
exports.hostName =  'http://localhost:5000';
exports.apiKey =    'REDACTED';

Can I know what is the problem 

also 
I really like this tool and I want to help to add some functionality 
Like set target temp for printing head or bed and any other functionality that may I need it 
"my programming skills not that much good but I like to help and improve my skills"

**Comment by OutsourcedGuru** [comment]
The octo-client assumes that you'll be connecting to a remote computer, hence the DNS name lookup. Try using the OctoPrint's hostname, presumably `octopi.local` and see if that works.

**Comment by Khalid-Alqahtani** [comment]
I used and it does not work 

is there any way to do it locally using the IP

**Comment by OutsourcedGuru** [comment]
I'll modify the code to allow the use of `localhost` to equal 127.0.0.1.

**Comment by Khalid-Alqahtani** [comment]
Thank you so much

**Comment by OutsourcedGuru** [comment]
Sorry, I didn't catch this before. The hostName variable isn't a URL so it shouldn't be decorated with "http://" before it.

```
exports.hostName = 'localhost';
exports.apiKey = 'REDACTED';
exports.port = 80;
```

The next version should support changing the default port to 5000.

**Comment by OutsourcedGuru** [comment]
Version 1.1.3 should now work with the new optional port config variable. Make sure to update your version. I've tested it using `localhost` before/after the update and this works (assuming that you don't try to put a URL like before).
