### ISSUE TITLE
Connect return "Success" also when it fail to connect 

### ISSUE THREAD

**Issue by Khalid-Alqahtani** [OutsourcedGuru/octo-client#3]
Hi 

I am using octo print and when I tried to use connect function it returns Success when it is actually established success connection but it also returns "Success" when it fails 

I tied it when the printer USB is unplugged

**Comment by OutsourcedGuru** [comment]
I've just walked through the installation instructions and I have a test rig here with octo-client v1.1.1.

## index.js (marked executable with `chmod a+x index.js`):
```
#!/usr/bin/env node

var OctoPrint = require('octo-client');

OctoPrint.printerState(function(response){
  console.log(response);
});
```

The Raspberry Pi 3B has OctoPrint v1.3.9 on it and a serial cable over to a Mega2560 board which I have removed. The board is powered on but within the OctoPrint interface, it is not connected yet. I have modified the API key as suggested in the instructions and the hostname is still `octopi.local` so I have left this alone in the config file.

```
./index.js
{ status: 'Printer is not operational' }
```

I now connect the cable and I press the Connect button in OctoPrint. The printer is now in the connected status.

```
./index.js
{ state: 
   { flags: 
      { cancelling: false,
        closedOrError: false,
        error: false,
        finishing: false,
        operational: true,
        paused: false,
        pausing: false,
        printing: false,
        ready: true,
        resuming: false,
        sdReady: false },
     text: 'Operational' },
  temperature: { tool0: { actual: 23.12, offset: 0, target: 0 } } }
```

So my rig looks like it is working.
